import { z } from 'zod';
export declare const EventStatus: z.ZodEnum<["draft", "scheduled", "published", "cancelled", "completed"]>;
export type EventStatus = z.infer<typeof EventStatus>;
export declare const EventVisibility: z.ZodEnum<["public", "unlisted", "members_only"]>;
export type EventVisibility = z.infer<typeof EventVisibility>;
export declare const EventCategory: z.ZodEnum<["service", "worship", "prayer", "youth", "kids", "small_group", "conference", "outreach", "social", "fundraiser", "class", "other"]>;
export type EventCategory = z.infer<typeof EventCategory>;
export declare const TicketTypeInput: z.ZodObject<{
    name: z.ZodString;
    description: z.ZodOptional<z.ZodString>;
    priceMinor: z.ZodNumber;
    currency: z.ZodEnum<["GBP", "EUR", "USD"]>;
    quantity: z.ZodNumber;
    perOrderMax: z.ZodDefault<z.ZodNumber>;
    salesStart: z.ZodOptional<z.ZodString>;
    salesEnd: z.ZodOptional<z.ZodString>;
}, "strip", z.ZodTypeAny, {
    name: string;
    currency: "GBP" | "EUR" | "USD";
    priceMinor: number;
    quantity: number;
    perOrderMax: number;
    description?: string | undefined;
    salesStart?: string | undefined;
    salesEnd?: string | undefined;
}, {
    name: string;
    currency: "GBP" | "EUR" | "USD";
    priceMinor: number;
    quantity: number;
    description?: string | undefined;
    perOrderMax?: number | undefined;
    salesStart?: string | undefined;
    salesEnd?: string | undefined;
}>;
export declare const VenueInput: z.ZodObject<{
    name: z.ZodString;
    addressLine1: z.ZodString;
    addressLine2: z.ZodOptional<z.ZodString>;
    city: z.ZodString;
    region: z.ZodOptional<z.ZodString>;
    postalCode: z.ZodString;
    country: z.ZodString;
    latitude: z.ZodOptional<z.ZodNumber>;
    longitude: z.ZodOptional<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    name: string;
    country: string;
    addressLine1: string;
    city: string;
    postalCode: string;
    addressLine2?: string | undefined;
    region?: string | undefined;
    latitude?: number | undefined;
    longitude?: number | undefined;
}, {
    name: string;
    country: string;
    addressLine1: string;
    city: string;
    postalCode: string;
    addressLine2?: string | undefined;
    region?: string | undefined;
    latitude?: number | undefined;
    longitude?: number | undefined;
}>;
export declare const CreateEventSchema: z.ZodEffects<z.ZodEffects<z.ZodObject<{
    title: z.ZodString;
    summary: z.ZodOptional<z.ZodString>;
    description: z.ZodOptional<z.ZodString>;
    category: z.ZodEnum<["service", "worship", "prayer", "youth", "kids", "small_group", "conference", "outreach", "social", "fundraiser", "class", "other"]>;
    visibility: z.ZodDefault<z.ZodEnum<["public", "unlisted", "members_only"]>>;
    startsAt: z.ZodString;
    endsAt: z.ZodString;
    timezone: z.ZodString;
    isOnline: z.ZodDefault<z.ZodBoolean>;
    onlineUrl: z.ZodOptional<z.ZodString>;
    venue: z.ZodOptional<z.ZodObject<{
        name: z.ZodString;
        addressLine1: z.ZodString;
        addressLine2: z.ZodOptional<z.ZodString>;
        city: z.ZodString;
        region: z.ZodOptional<z.ZodString>;
        postalCode: z.ZodString;
        country: z.ZodString;
        latitude: z.ZodOptional<z.ZodNumber>;
        longitude: z.ZodOptional<z.ZodNumber>;
    }, "strip", z.ZodTypeAny, {
        name: string;
        country: string;
        addressLine1: string;
        city: string;
        postalCode: string;
        addressLine2?: string | undefined;
        region?: string | undefined;
        latitude?: number | undefined;
        longitude?: number | undefined;
    }, {
        name: string;
        country: string;
        addressLine1: string;
        city: string;
        postalCode: string;
        addressLine2?: string | undefined;
        region?: string | undefined;
        latitude?: number | undefined;
        longitude?: number | undefined;
    }>>;
    capacity: z.ZodOptional<z.ZodNumber>;
    coverImageUrl: z.ZodOptional<z.ZodString>;
    ticketTypes: z.ZodDefault<z.ZodArray<z.ZodObject<{
        name: z.ZodString;
        description: z.ZodOptional<z.ZodString>;
        priceMinor: z.ZodNumber;
        currency: z.ZodEnum<["GBP", "EUR", "USD"]>;
        quantity: z.ZodNumber;
        perOrderMax: z.ZodDefault<z.ZodNumber>;
        salesStart: z.ZodOptional<z.ZodString>;
        salesEnd: z.ZodOptional<z.ZodString>;
    }, "strip", z.ZodTypeAny, {
        name: string;
        currency: "GBP" | "EUR" | "USD";
        priceMinor: number;
        quantity: number;
        perOrderMax: number;
        description?: string | undefined;
        salesStart?: string | undefined;
        salesEnd?: string | undefined;
    }, {
        name: string;
        currency: "GBP" | "EUR" | "USD";
        priceMinor: number;
        quantity: number;
        description?: string | undefined;
        perOrderMax?: number | undefined;
        salesStart?: string | undefined;
        salesEnd?: string | undefined;
    }>, "many">>;
}, "strip", z.ZodTypeAny, {
    title: string;
    category: "social" | "service" | "worship" | "prayer" | "youth" | "kids" | "small_group" | "conference" | "outreach" | "fundraiser" | "class" | "other";
    visibility: "public" | "unlisted" | "members_only";
    startsAt: string;
    endsAt: string;
    timezone: string;
    isOnline: boolean;
    ticketTypes: {
        name: string;
        currency: "GBP" | "EUR" | "USD";
        priceMinor: number;
        quantity: number;
        perOrderMax: number;
        description?: string | undefined;
        salesStart?: string | undefined;
        salesEnd?: string | undefined;
    }[];
    venue?: {
        name: string;
        country: string;
        addressLine1: string;
        city: string;
        postalCode: string;
        addressLine2?: string | undefined;
        region?: string | undefined;
        latitude?: number | undefined;
        longitude?: number | undefined;
    } | undefined;
    description?: string | undefined;
    summary?: string | undefined;
    onlineUrl?: string | undefined;
    capacity?: number | undefined;
    coverImageUrl?: string | undefined;
}, {
    title: string;
    category: "social" | "service" | "worship" | "prayer" | "youth" | "kids" | "small_group" | "conference" | "outreach" | "fundraiser" | "class" | "other";
    startsAt: string;
    endsAt: string;
    timezone: string;
    venue?: {
        name: string;
        country: string;
        addressLine1: string;
        city: string;
        postalCode: string;
        addressLine2?: string | undefined;
        region?: string | undefined;
        latitude?: number | undefined;
        longitude?: number | undefined;
    } | undefined;
    description?: string | undefined;
    summary?: string | undefined;
    visibility?: "public" | "unlisted" | "members_only" | undefined;
    isOnline?: boolean | undefined;
    onlineUrl?: string | undefined;
    capacity?: number | undefined;
    coverImageUrl?: string | undefined;
    ticketTypes?: {
        name: string;
        currency: "GBP" | "EUR" | "USD";
        priceMinor: number;
        quantity: number;
        description?: string | undefined;
        perOrderMax?: number | undefined;
        salesStart?: string | undefined;
        salesEnd?: string | undefined;
    }[] | undefined;
}>, {
    title: string;
    category: "social" | "service" | "worship" | "prayer" | "youth" | "kids" | "small_group" | "conference" | "outreach" | "fundraiser" | "class" | "other";
    visibility: "public" | "unlisted" | "members_only";
    startsAt: string;
    endsAt: string;
    timezone: string;
    isOnline: boolean;
    ticketTypes: {
        name: string;
        currency: "GBP" | "EUR" | "USD";
        priceMinor: number;
        quantity: number;
        perOrderMax: number;
        description?: string | undefined;
        salesStart?: string | undefined;
        salesEnd?: string | undefined;
    }[];
    venue?: {
        name: string;
        country: string;
        addressLine1: string;
        city: string;
        postalCode: string;
        addressLine2?: string | undefined;
        region?: string | undefined;
        latitude?: number | undefined;
        longitude?: number | undefined;
    } | undefined;
    description?: string | undefined;
    summary?: string | undefined;
    onlineUrl?: string | undefined;
    capacity?: number | undefined;
    coverImageUrl?: string | undefined;
}, {
    title: string;
    category: "social" | "service" | "worship" | "prayer" | "youth" | "kids" | "small_group" | "conference" | "outreach" | "fundraiser" | "class" | "other";
    startsAt: string;
    endsAt: string;
    timezone: string;
    venue?: {
        name: string;
        country: string;
        addressLine1: string;
        city: string;
        postalCode: string;
        addressLine2?: string | undefined;
        region?: string | undefined;
        latitude?: number | undefined;
        longitude?: number | undefined;
    } | undefined;
    description?: string | undefined;
    summary?: string | undefined;
    visibility?: "public" | "unlisted" | "members_only" | undefined;
    isOnline?: boolean | undefined;
    onlineUrl?: string | undefined;
    capacity?: number | undefined;
    coverImageUrl?: string | undefined;
    ticketTypes?: {
        name: string;
        currency: "GBP" | "EUR" | "USD";
        priceMinor: number;
        quantity: number;
        description?: string | undefined;
        perOrderMax?: number | undefined;
        salesStart?: string | undefined;
        salesEnd?: string | undefined;
    }[] | undefined;
}>, {
    title: string;
    category: "social" | "service" | "worship" | "prayer" | "youth" | "kids" | "small_group" | "conference" | "outreach" | "fundraiser" | "class" | "other";
    visibility: "public" | "unlisted" | "members_only";
    startsAt: string;
    endsAt: string;
    timezone: string;
    isOnline: boolean;
    ticketTypes: {
        name: string;
        currency: "GBP" | "EUR" | "USD";
        priceMinor: number;
        quantity: number;
        perOrderMax: number;
        description?: string | undefined;
        salesStart?: string | undefined;
        salesEnd?: string | undefined;
    }[];
    venue?: {
        name: string;
        country: string;
        addressLine1: string;
        city: string;
        postalCode: string;
        addressLine2?: string | undefined;
        region?: string | undefined;
        latitude?: number | undefined;
        longitude?: number | undefined;
    } | undefined;
    description?: string | undefined;
    summary?: string | undefined;
    onlineUrl?: string | undefined;
    capacity?: number | undefined;
    coverImageUrl?: string | undefined;
}, {
    title: string;
    category: "social" | "service" | "worship" | "prayer" | "youth" | "kids" | "small_group" | "conference" | "outreach" | "fundraiser" | "class" | "other";
    startsAt: string;
    endsAt: string;
    timezone: string;
    venue?: {
        name: string;
        country: string;
        addressLine1: string;
        city: string;
        postalCode: string;
        addressLine2?: string | undefined;
        region?: string | undefined;
        latitude?: number | undefined;
        longitude?: number | undefined;
    } | undefined;
    description?: string | undefined;
    summary?: string | undefined;
    visibility?: "public" | "unlisted" | "members_only" | undefined;
    isOnline?: boolean | undefined;
    onlineUrl?: string | undefined;
    capacity?: number | undefined;
    coverImageUrl?: string | undefined;
    ticketTypes?: {
        name: string;
        currency: "GBP" | "EUR" | "USD";
        priceMinor: number;
        quantity: number;
        description?: string | undefined;
        perOrderMax?: number | undefined;
        salesStart?: string | undefined;
        salesEnd?: string | undefined;
    }[] | undefined;
}>;
export type CreateEventInput = z.infer<typeof CreateEventSchema>;
export declare const EventSearchSchema: z.ZodObject<{
    q: z.ZodOptional<z.ZodString>;
    category: z.ZodOptional<z.ZodEnum<["service", "worship", "prayer", "youth", "kids", "small_group", "conference", "outreach", "social", "fundraiser", "class", "other"]>>;
    country: z.ZodOptional<z.ZodString>;
    city: z.ZodOptional<z.ZodString>;
    startsAfter: z.ZodOptional<z.ZodString>;
    startsBefore: z.ZodOptional<z.ZodString>;
    free: z.ZodOptional<z.ZodBoolean>;
    cursor: z.ZodOptional<z.ZodString>;
    limit: z.ZodDefault<z.ZodNumber>;
}, "strip", z.ZodTypeAny, {
    limit: number;
    cursor?: string | undefined;
    country?: string | undefined;
    city?: string | undefined;
    category?: "social" | "service" | "worship" | "prayer" | "youth" | "kids" | "small_group" | "conference" | "outreach" | "fundraiser" | "class" | "other" | undefined;
    q?: string | undefined;
    startsAfter?: string | undefined;
    startsBefore?: string | undefined;
    free?: boolean | undefined;
}, {
    cursor?: string | undefined;
    country?: string | undefined;
    city?: string | undefined;
    category?: "social" | "service" | "worship" | "prayer" | "youth" | "kids" | "small_group" | "conference" | "outreach" | "fundraiser" | "class" | "other" | undefined;
    q?: string | undefined;
    startsAfter?: string | undefined;
    startsBefore?: string | undefined;
    free?: boolean | undefined;
    limit?: number | undefined;
}>;
export type EventSearchInput = z.infer<typeof EventSearchSchema>;
//# sourceMappingURL=event.d.ts.map